### PR TITLE
Full image crop generator

### PR DESCRIPTION
**Pull request by Arkkienkeli**
https://github.com/cytomining/DeepProfiler/issues/320

### CODE REVIEW

**Comment by Arkkienkeli** [comment]
Things to add\change:

1.  `np.resize` probably should be changed.
2. `area_coverage` is not used now. 
3.  Do we want to take into account the aspect ratio? The good method appeared in TF 2.8  https://tensorflow.google.cn/api_docs/python/tf/keras/preprocessing/image/smart_resize

**Comment by jccaicedo** [comment]
I made some changes. I agree that np.resize needed to be changed, but the replacement I made is too slow now. We need to investigate more how to accelerate it.

**Comment by jccaicedo** [comment]
@Arkkienkeli The branch is ready for full-image analysis, it is working well both for training and profiling. What we need to make sure now is that this branch does not break anything with single-cell training and profiling. Please, run a few tests with single cells in this branch and if it works, feel free to merge!

**Review by jccaicedo — APPROVED** [review]
Looks good to me!

**Pull request merged**
