### PR TITLE
Fix tests

### PR DESCRIPTION
**Pull request by Arkkienkeli**

### CODE REVIEW

**Review by jccaicedo — COMMENTED** [review]
Looks good! But I got 5 tests failing when running pytest in my environment. Can you confirm everything passes in your end?

**Comment by Arkkienkeli** [comment]
Yes, everything passes the tests locally.
Could you show the log of pytest?

**Comment by jccaicedo** [comment]
Everything before and after passes OK.
```
* tests/deepprofiler/learning/test_model.py::test_train FAILED                                                                                  [ 68%]
  tests/deepprofiler/learning/test_profiling.py::test_init PASSED                                                                               [ 70%]
  tests/deepprofiler/learning/test_profiling.py::test_configure PASSED                                                                          [ 71%]
  tests/deepprofiler/learning/test_profiling.py::test_check PASSED                                                                              [ 72%]
* tests/deepprofiler/learning/test_profiling.py::test_extract_features FAILED                                                                   [ 73%]
* tests/deepprofiler/learning/test_profiling.py::test_profile FAILED                                                                            [ 74%]
* tests/deepprofiler/learning/test_training.py::test_learn_model FAILED                                                                         [ 75%]
  tests/deepprofiler/learning/test_validation.py::test_init PASSED                                                                              [ 77%]
  tests/deepprofiler/learning/test_validation.py::test_load_validation_data PASSED                                                              [ 78%]
  tests/plugins/crop_generators/test_autoencoder_crop_generator.py::test_autoencoder_crop_generator PASSED                                      [ 79%]
  tests/plugins/crop_generators/test_autoencoder_crop_generator.py::test_generator_class_generate PASSED                                        [ 80%]
  tests/plugins/crop_generators/test_autoencoder_crop_generator.py::test_single_image_generator_class_generate PASSED                           [ 81%]
  tests/plugins/crop_generators/test_crop_generator.py::test_crop_generator PASSED                                                              [ 82%]
  tests/plugins/crop_generators/test_mixup_crop_generator.py::test_init_mixup PASSED                                                            [ 83%]
  tests/plugins/crop_generators/test_mixup_crop_generator.py::test_add_crops PASSED                                                             [ 85%]
* tests/plugins/crop_generators/test_mixup_crop_generator.py::test_batch_mixup FAILED                                                           [ 86%]
```

**Comment by jccaicedo** [comment]
Thanks for checking Nikita! According to your suggestion, it's important to run pytest in a GPU device that is free.
We can do that as follows:
```
CUDA_VISIBLE_DEVICES=1 pytest
```
Now all the tests run correctly. Feel free to merge and resolve.

**Pull request merged**
