### PR TITLE
Tf2 folder structure

### PR DESCRIPTION
**Pull request by michaelbornholdt**
This commit will solve the issue https://github.com/cytomining/DeepProfiler/issues/264 which is concerned with the folder structure of profiling and cropping. 

I am only applying this to tf2 since this will be the active branch of development and will be needed for the JUMP projects.

### CODE REVIEW

**Comment by michaelbornholdt** [comment]
@shntnu @jccaicedo @Arkkienkeli 
Nikita, do you want to review this? 

I am unaware of any coding ettiquete for DP so I have not run Black or anything similar... even tho the code could use that :)

**Comment by michaelbornholdt** [comment]
I have also run pytest on the full project, and all 86 items pass.

**Comment by Arkkienkeli** [comment]
Hey @michaelbornholdt , I have reviewed this, tests and example data seem to work for me also. 
One very minor thing, the output of the feature path is currently old:
https://github.com/cytomining/DeepProfiler/pull/265/files#diff-812298ddf62b5a2d607e69c630b0e4d3f6b9c94eb511714362800ab7f4cc3c23R100

Could you change it?

Also, regarding this https://github.com/cytomining/DeepProfiler/pull/265/files#diff-a02b2a7181916ba2df9f2574c84812f902ef9f93ffc37399a095d016166be9c5R25
This is not general solution, but changing image keys will require to change them everywhere in DeepProfiler, as we discussed with @michaelbornholdt  ; so let it be like this for now, I guess.

**Comment by michaelbornholdt** [comment]
@Arkkienkeli 
> One very minor thing, the output of the feature path is currently old
Don't know what you mean by this. What line are you referring to?

**Comment by Arkkienkeli** [comment]
This one: https://github.com/cytomining/DeepProfiler/blob/1ac1d7d03e8b0aa360c1d88a9bebd330401bdaf2/deepprofiler/learning/profiling.py#L100

**Review by jccaicedo — APPROVED** [review]

**Comment by jccaicedo** [comment]
The `image_key` is a string, so it should be OK to replace `-` with `/` where necessary. 
The code looks good to me, I'm going to attempt a merge and resolve any conflicts we may have.

**Pull request merged**
