### PR TITLE
Changed tensorflow imports and tensorflow + python requirements

### PR DESCRIPTION
**Pull request by diskontinuum**
Modified tf imports to import tf2 but run only tf1. Added tf 2.1.*  to requirements and specified python requirement as <3.8

### CODE REVIEW

**Comment by Arkkienkeli** [comment]
@diskontinuum 
Hi, it probably should be ```"tensorflow==2.1.*"``` instead of ```"tensorflow-cpu==2.1.*"``` in the requirements.

**Comment by diskontinuum** [comment]
I agree on the tensorflow==2.1.* . However, I did not find a way to better specify both upper and lower bounds on the python version. I was assuming this would work because of this example: https://packaging.python.org/discussions/install-requires-vs-requirements/ .

**Comment by Arkkienkeli** [comment]
@diskontinuum 
Yes, but pytest is a separate package, it is not a python itself. 
I think we can just add the python version requirement to README.

**Comment by Arkkienkeli** [comment]
@diskontinuum 
I had to revert it as more changes are needed so the code could run.

**Pull request merged**
