### PR TITLE
Use correct min/max stretching, and guard against flat images

### PR DESCRIPTION
**Pull request by thouis**
The min/max stretching was using (im - min) / max, instead of (im - min) / (max - min).  This change fixes that stretch, and also adds a small epsilon to guard against NaNs when max == min.

### CODE REVIEW

**Comment by thouis** [comment]
I also added a check for the image size matching the configured size, and a warning for cell boxes entirely outside the image.

These changes all originated from the same run,
With a misconfigured image size,
That led to clipping boxes outside the image,
Which produced all-zeros images,
Which produced NaNs in the image normalization.

**Comment by thouis** [comment]
The assertion on image size could be ignored if you first incorporate this PR: https://github.com/cytomining/DeepProfiler/pull/354

**Review by jccaicedo — APPROVED** [review]
Looks good to me!

**Comment by jccaicedo** [comment]
Thank you for the PR!! This is amazing!

**Pull request merged**
